name: Get Concurrency Options

description: Get concurrency options for the running job

outputs:
  group:
    description: The concurrency group name for the running job
    value: ${{ steps.get-concurrency-opts.outputs.group }}
  cancel-in-progress:
    description: >
      Whether to cancel any currently running job in the same concurrency group
      or not
    value: ${{ steps.get-concurrency-opts.outputs.cancel-in-progress }}

runs:
  using: composite
  steps:
    - id: get-concurrency-opts
      env:
        CANCEL_IN_PROGRESS: ${{ github.ref != 'refs/heads/master' &&
          !startsWith(github.ref, 'refs/heads/1.') &&
          !startsWith(github.ref, 'refs/heads/2.') }}
      run: |
        if [ $CANCEL_IN_PROGRESS = true ]; then
          GROUP=${{ github.workflow }}-${{ github.ref }}
        else
          GROUP=${{ github.workflow }}-${{ github.sha }}
        fi

        echo "::set-output name=group::$GROUP"
        echo "::set-output name=cancel-in-progress::$CANCEL_IN_PROGRESS"
      shell: bash
