name: 'Pack and Deploy'
description: 'Pack and deploy the package'
runs:
  using: "composite"
  steps:
    - run: |
        # Our testing expects that the init process (PID 1) will
        # reap orphan processes. At least the following test leans
        # on it: app-tap/gh-4983-tnt-e-assert-false-hangs.test.lua.
        export PACKPACK_EXTRA_DOCKER_RUN_PARAMS='--init'
        #
        # Create packages.
        make -f .gitlab.mk package
        #
        # Deploy packages.
        case ${{ github.ref }} in
          refs/tags/*-alpha*|refs/tags/*-beta*|refs/tags/*-rc*)
            export REPO_S3_DIR=pre-release
            ;;
          refs/tags/*)
            export REPO_S3_DIR=release
            ;;
        esac
        if [ -n "${REPO_S3_DIR}" ]; then
          make -f .gitlab.mk deploy
        fi
      shell: bash
